# encoding: utf-8
module Mobit
  module Core
    module CountryCode

      CODES = [
        {name: 'Afghanistan', iso: 'AF', iso2: 'AFG', code: '93', trunk_code: '0'},
        {name: 'Albania', iso: 'AL', iso2: 'ALB', code: '355', trunk_code: '0'},
        {name: 'Algeria', iso: 'DZ', iso2: 'DZA', code: '213', trunk_code: '0'},
        {name: 'American Samoa', iso: 'AS', iso2: 'ASM', code: '1684', trunk_code: '1'},
        {name: 'Andorra', iso: 'AD', iso2: 'AND', code: '376', trunk_code: ''},
        {name: 'Angola', iso: 'AO', iso2: 'AGO', code: '244', trunk_code: ''},
        {name: 'Anguilla', iso: 'AI', iso2: 'AIA', code: '1264', trunk_code: '1'},
        {name: 'Antarctica', iso: 'AQ', iso2: 'ATA', code: '672', trunk_code: ''},
        {name: 'Antigua and Barbuda', iso: 'AG', iso2: 'ATG', code: '1268', trunk_code: '1'},
        {name: 'Argentina', iso: 'AR', iso2: 'ARG', code: '54', trunk_code: '0'},
        {name: 'Armenia', iso: 'AM', iso2: 'ARM', code: '374', trunk_code: '0'},
        {name: 'Aruba', iso: 'AW', iso2: 'ABW', code: '297', trunk_code: ''},
        {name: 'Australia', iso: 'AU', iso2: 'AUS', code: '61', trunk_code: '0'},
        {name: 'Austria', iso: 'AT', iso2: 'AUT', code: '43', trunk_code: '0'},
        {name: 'Azerbaijan', iso: 'AZ', iso2: 'AZE', code: '994', trunk_code: '0'},

        {name: 'Bahamas', iso: 'BS', iso2: 'BHS', code: '1242', trunk_code: '1'},
        {name: 'Bahrain', iso: 'BH', iso2: 'BHR', code: '973', trunk_code: ''},
        {name: 'Bangladesh', iso: 'BD', iso2: 'BGD', code: '880', trunk_code: '0'},
        {name: 'Barbados', iso: 'BB', iso2: 'BRB', code: '1246', trunk_code: '1'},
        {name: 'Belarus', iso: 'BY', iso2: 'BLR', code: '375', trunk_code: '80'},
        {name: 'Belgium', iso: 'BE', iso2: 'BEL', code: '32', trunk_code: '0'},
        {name: 'Belize', iso: 'BZ', iso2: 'BLZ', code: '501', trunk_code: ''},
        {name: 'Benin', iso: 'BJ', iso2: 'BEN', code: '229', trunk_code: ''},
        {name: 'Bermuda', iso: 'BM', iso2: 'BMU', code: '1441', trunk_code: '1'},
        {name: 'Bhutan', iso: 'BT', iso2: 'BTN', code: '975', trunk_code: ''},
        {name: 'Bolivia', iso: 'BO', iso2: 'BOL', code: '591', trunk_code: '0'},
        {name: 'Bosnia and Herzegovina', iso: 'BA', iso2: 'BIH', code: '387', trunk_code: '0'},
        {name: 'Botswana', iso: 'BW', iso2: 'BWA', code: '267', trunk_code: ''},
        {name: 'Brazil', iso: 'BR', iso2: 'BRA', code: '55', trunk_code: '0'},
        {name: 'British Indian Ocean Territory', iso: 'IO', iso2: 'IOT', code: '', trunk_code: ''},
        {name: 'British Virgin Islands', iso: 'VG', iso2: 'VGB', code: '1284', trunk_code: '0'},
        {name: 'Brunei', iso: 'BN', iso2: 'BRN', code: '673', trunk_code: ''},
        {name: 'Bulgaria', iso: 'BG', iso2: 'BGR', code: '359', trunk_code: '0'},
        {name: 'Burkina Faso', iso: 'BF', iso2: 'BFA', code: '226', trunk_code: ''},
        {name: 'Burma(Myanmar)', iso: 'MM', iso2: 'MMR', code: '95', trunk_code: ''},
        {name: 'Burundi', iso: 'BI', iso2: 'BDI', code: '257', trunk_code: ''},

        {name: 'Cambodia', iso: 'KH', iso2: 'KHM', code: '855', trunk_code: '0'},
        {name: 'Cameroon', iso: 'CM', iso2: 'CMR', code: '237', trunk_code: ''},
        {name: 'Canada', iso: 'CA', iso2: 'CAN', code: '1', trunk_code: '1'},
        {name: 'Cape Verde', iso: 'CV', iso2: 'CPV', code: '238', trunk_code: ''},
        {name: 'Cayman Islands', iso: 'KY', iso2: 'CYM', code: '1345', trunk_code: '1'},
        {name: 'Central African Republic', iso: 'CF', iso2: 'CAF', code: '236', trunk_code: ''},
        {name: 'Chad', iso: 'TD', iso2: 'TCD', code: '235', trunk_code: ''},
        {name: 'Chile', iso: 'CL', iso2: 'CHL', code: '56', trunk_code: '0'},
        {name: 'China', iso: 'CN', iso2: 'CHN', code: '86', trunk_code: '0'},
        {name: 'Christmas Island', iso: 'CX', iso2: 'CXR', code: '61', trunk_code: ''},
        {name: 'Cocos(Keeling)Islands', iso: 'CC', iso2: 'CCK', code: '61', trunk_code: ''},
        {name: 'Colombia', iso: 'CO', iso2: 'COL', code: '57', trunk_code: '0'},
        {name: 'Comoros', iso: 'KM', iso2: 'COM', code: '269', trunk_code: ''},
        {name: 'Cook Islands', iso: 'CK', iso2: 'COK', code: '682', trunk_code: ''},
        {name: 'Costa Rica', iso: 'CR', iso2: 'CRC', code: '506', trunk_code: ''},
        {name: 'Croatia', iso: 'HR', iso2: 'HRV', code: '385', trunk_code: '0'},
        {name: 'Cuba', iso: 'CU', iso2: 'CUB', code: '53', trunk_code: '0'},
        {name: 'Cyprus', iso: 'CY', iso2: 'CYP', code: '357', trunk_code: ''},
        {name: 'Czech Republic', iso: 'CZ', iso2: 'CZE', code: '420', trunk_code: ''},

        {name: 'Democratic Republic of the Congo', iso: 'CD', iso2: 'COD', code: '243', trunk_code: '0'},
        {name: 'Denmark', iso: 'DK', iso2: 'DNK', code: '45', trunk_code: ''},
        {name: 'Djibouti', iso: 'DJ', iso2: 'DJI', code: '253', trunk_code: ''},
        {name: 'Dominica', iso: 'DM', iso2: 'DMA', code: '1767', trunk_code: '1'},
        {name: 'Dominican Republic', iso: 'DO', iso2: 'DOM', code: '1809', trunk_code: '1'},

        {name: 'Ecuador', iso: 'EC', iso2: 'ECU', code: '593', trunk_code: '0'},
        {name: 'Egypt', iso: 'EG', iso2: 'EGY', code: '20', trunk_code: '0'},
        {name: 'El Salvador', iso: 'SV', iso2: 'SLV', code: '503', trunk_code: ''},
        {name: 'Equatorial Guinea', iso: 'GQ', iso2: 'GNQ', code: '240', trunk_code: ''},
        {name: 'Eritrea', iso: 'ER', iso2: 'ERI', code: '291', trunk_code: '0'},
        {name: 'Estonia', iso: 'EE', iso2: 'EST', code: '372', trunk_code: ''},
        {name: 'Ethiopia', iso: 'ET', iso2: 'ETH', code: '251', trunk_code: '0'},

        {name: 'Falkland Islands', iso: 'FK', iso2: 'FLK', code: '500', trunk_code: ''},
        {name: 'Faroe Islands', iso: 'FO', iso2: 'FRO', code: '298', trunk_code: ''},
        {name: 'Fiji', iso: 'FJ', iso2: 'FJI', code: '679', trunk_code: ''},
        {name: 'Finland', iso: 'FI', iso2: 'FIN', code: '358', trunk_code: '0'},
        {name: 'France', iso: 'FR', iso2: 'FRA', code: '33', trunk_code: '0'},
        # {name: 'French Guiana', iso: '', iso2: '', code: '594', trunk_code: '0'},
        {name: 'French Polynesia', iso: 'PF', iso2: 'PYF', code: '689', trunk_code: ''},

        {name: 'Gabon', iso: 'GA', iso2: 'GAB', code: '241', trunk_code: ''},
        {name: 'Gambia', iso: 'GM', iso2: 'GMB', code: '220', trunk_code: ''},
        {name: 'Gaza Strip', iso: '/', code: '970', trunk_code: ''},
        {name: 'Georgia', iso: 'GE', iso2: 'GEO', code: '995', trunk_code: '0'},
        {name: 'Germany', iso: 'DE', iso2: 'DEU', code: '49', trunk_code: '0'},
        {name: 'Ghana', iso: 'GH', iso2: 'GHA', code: '233', trunk_code: '0'},
        {name: 'Gibraltar', iso: 'GI', iso2: 'GIB', code: '350', trunk_code: ''},
        {name: 'Greece', iso: 'GR', iso2: 'GRC', code: '30', trunk_code: ''},
        {name: 'Greenland', iso: 'GL', iso2: 'GRL', code: '299', trunk_code: ''},
        {name: 'Grenada', iso: 'GD', iso2: 'GRD', code: '1473', trunk_code: '1'},
        {name: 'Guam', iso: 'GU', iso2: 'GUM', code: '1671', trunk_code: '1'},
        {name: 'Guatemala', iso: 'GT', iso2: 'GTM', code: '502', trunk_code: ''},
        {name: 'Guinea', iso: 'GN', iso2: 'GIN', code: '224', trunk_code: ''},
        {name: 'Guinea-Bissau', iso: 'GW', iso2: 'GNB', code: '245', trunk_code: ''},
        {name: 'Guyana', iso: 'GY', iso2: 'GUY', code: '592', trunk_code: ''},

        {name: 'Haiti', iso: 'HT', iso2: 'HTI', code: '509', trunk_code: ''},
        {name: 'Holy See (Vatican City)	', iso: 'VA', iso2: 'VAT', code: '39', trunk_code: ''},
        {name: 'Honduras', iso: 'HN', iso2: 'HND', code: '504', trunk_code: ''},
        {name: 'Hong Kong', iso: 'HK', iso2: 'HKG', code: '852', trunk_code: ''},
        {name: 'Hungary', iso: 'HU', iso2: 'HUN', code: '36', trunk_code: '06'},

        {name: 'Iceland', iso: 'IS', iso2: 'IS', code: '354', trunk_code: ''},
        {name: 'India', iso: 'IN', iso2: 'IND', code: '91', trunk_code: '0'},
        {name: 'Indonesia', iso: 'ID', iso2: 'IDN', code: '62', trunk_code: '0'},
        {name: 'Iran', iso: 'IR', iso2: 'IRN', code: '98', trunk_code: '0'},
        {name: 'Iraq', iso: 'IQ', iso2: 'IRQ', code: '964', trunk_code: ''},
        {name: 'Ireland', iso: 'IE', iso2: 'IRL', code: '353', trunk_code: '0'},
        {name: 'Isle of Man', iso: 'IM', iso2: 'IMN', code: '44', trunk_code: ''},
        {name: 'Israel', iso: 'IL', iso2: 'ISR', code: '972', trunk_code: '0'},
        {name: 'Italy', iso: 'IT', iso2: 'ITA', code: '39', trunk_code: ''},
        {name: 'Ivory Coast', iso: 'CI', iso2: 'CIV', code: '225', trunk_code: ''},

        {name: 'Jamaica', iso: 'JM', iso2: 'JAM', code: '1876', trunk_code: '1'},
        {name: 'Japan', iso: 'JP', iso2: 'JPN', code: '81', trunk_code: '0'},
        {name: 'Jersey', iso: 'JE', iso2: 'JEY', code: '', trunk_code: ''},
        {name: 'Jordan', iso: 'JO', iso2: 'JOR', code: '962', trunk_code: '0'},

        {name: 'Kazakhstan	', iso: 'KZ', iso2: 'KAZ', code: '7', trunk_code: '8'},
        {name: 'Kenya', iso: 'KE', iso2: 'KEN', code: '254', trunk_code: '0'},
        {name: 'Kiribati', iso: 'KI', iso2: 'KIR', code: '686', trunk_code: ''},
        {name: 'Kosovo', iso: '/', code: '381', trunk_code: ''},
        {name: 'Kuwait	', iso: 'KW', iso2: 'KWT', code: '965', trunk_code: ''},
        {name: 'Kyrgyzstan	', iso: 'KG', iso2: 'KGZ', code: '996', trunk_code: '0'},

        {name: 'Laos', iso: 'LA', iso2: 'LAO', code: '856', trunk_code: '0'},
        {name: 'Latvia', iso: 'LV', iso2: 'LVA', code: '371', trunk_code: ''},
        {name: 'Lebanon', iso: 'LB', iso2: 'LBN', code: '961', trunk_code: '0'},
        {name: 'Lesotho', iso: 'LS', iso2: 'LSO', code: '266', trunk_code: ''},
        {name: 'Liberia', iso: 'LR', iso2: 'LBR', code: '231', trunk_code: ''},
        {name: 'Libya', iso: 'LY', iso2: 'LBY', code: '218', trunk_code: '0'},
        {name: 'Liechtenstein', iso: 'LI', iso2: 'LIE', code: '423', trunk_code: ''},
        {name: 'Lithuania', iso: 'LT', iso2: 'LTU', code: '370', trunk_code: '8'},
        {name: 'Luxembourg', iso: 'LU', iso2: 'LUX', code: '352', trunk_code: ''},

        {name: 'Macau', iso: 'MO', iso2: 'MAC', code: '853', trunk_code: ''},
        {name: 'Macedonia', iso: 'MK', iso2: 'MKD', code: '389', trunk_code: '0'},
        {name: 'Madagascar', iso: 'MG', iso2: 'MDG', code: '261', trunk_code: '0'},
        {name: 'Malawi', iso: 'MW', iso2: 'MWI', code: '265', trunk_code: ''},
        {name: 'Malaysia', iso: 'MY', iso2: 'MYS', code: '60', trunk_code: '0'},
        {name: 'Maldives', iso: 'MV', iso2: 'MDV', code: '960', trunk_code: ''},
        {name: 'Mali', iso: 'ML', iso2: 'MLI', code: '223', trunk_code: ''},
        {name: 'Malta', iso: 'MT', iso2: 'MLT', code: '356', trunk_code: ''},
        {name: 'Marshall Islands', iso: 'MH', iso2: 'MHL', code: '692', trunk_code: '1'},
        {name: 'Mauritania', iso: 'MR', iso2: 'MRT', code: '222', trunk_code: ''},
        {name: 'Mauritius', iso: 'MU', iso2: 'MUS', code: '230', trunk_code: ''},
        {name: 'Mayotte', iso: 'YT', iso2: 'MYT', code: '262', trunk_code: ''},
        {name: 'Mexico', iso: 'MX', iso2: 'MEX', code: '52', trunk_code: '01'},
        {name: 'Micronesia', iso: 'FM', iso2: 'FSM', code: '691', trunk_code: '1'},
        {name: 'Moldova', iso: 'MD', iso2: 'MDA', code: '373', trunk_code: '0'},
        {name: 'Monaco', iso: 'MC', iso2: 'MCO', code: '377', trunk_code: ''},
        {name: 'Mongolia', iso: 'MN', iso2: 'MNG', code: '976', trunk_code: '0'},
        {name: 'Montenegro', iso: 'ME', iso2: 'MNE', code: '382', trunk_code: '0'},
        {name: 'Montserrat', iso: 'MS', iso2: 'MSR', code: '1664', trunk_code: '1'},
        {name: 'Morocco', iso: 'MA', iso2: 'MAR', code: '212', trunk_code: '0'},
        {name: 'Mozambique', iso: 'MZ', iso2: 'MOZ', code: '258', trunk_code: ''},

        {name: 'Namibia', iso: 'NA', iso2: 'NAM', code: '264', trunk_code: '0'},
        {name: 'Nauru', iso: 'NR', iso2: 'NRU', code: '674', trunk_code: ''},
        {name: 'Nepal', iso: 'NP', iso2: 'NPL', code: '977', trunk_code: '0'},
        {name: 'Netherlands', iso: 'NL', iso2: 'NLD', code: '31', trunk_code: '0'},
        {name: 'Netherlands Antilles', iso: 'AN', iso2: 'ANT', code: '599', trunk_code: '0'},
        {name: 'New Caledonia', iso: 'NC', iso2: 'NCL', code: '687', trunk_code: ''},
        {name: 'New Zealand', iso: 'NZ', iso2: 'NZL', code: '64', trunk_code: '0'},
        {name: 'Nicaragua', iso: 'NI', iso2: 'NIC', code: '505', trunk_code: ''},
        {name: 'Niger', iso: 'NE', iso2: 'NER', code: '227', trunk_code: ''},
        {name: 'Nigeria', iso: 'NG', iso2: 'NGA', code: '234', trunk_code: '0'},
        {name: 'Niue', iso: 'NU', iso2: 'NIU', code: '683', trunk_code: ''},

        # {name: 'Norfolk Island', iso: '', iso2: 'NFK', code: '672', trunk_code: '0'},
        {name: 'North Korea', iso: 'KP', iso2: 'PRK', code: '850', trunk_code: ''},
        {name: 'Northern Mariana Islands', iso: 'MP', iso2: 'MNP', code: '1670', trunk_code: '1'},
        {name: 'Norway', iso: 'NO', iso2: 'NOR', code: '47', trunk_code: ''},

        {name: 'Oman', iso: 'OM', iso2: 'OMN', code: '968', trunk_code: ''},

        {name: 'Pakistan', iso: 'PK', iso2: 'PAK', code: '92', trunk_code: '0'},
        {name: 'Palau', iso: 'PW', iso2: 'PLW', code: '680', trunk_code: ''},
        {name: 'Panama', iso: 'PA', iso2: 'PAN', code: '507', trunk_code: ''},
        {name: 'Papua New Guinea', iso: 'PG', iso2: 'PNG', code: '675', trunk_code: ''},
        {name: 'Paraguay', iso: 'PY', iso2: 'PRY', code: '595', trunk_code: '0'},
        {name: 'Peru', iso: 'PE', iso2: 'PER', code: '51', trunk_code: '0'},
        {name: 'Philippines', iso: 'PH', iso2: 'PHL', code: '63', trunk_code: '0'},
        {name: 'Pitcairn Islands', iso: 'PN', iso2: 'PCN', code: '870', trunk_code: ''},
        {name: 'Poland', iso: 'PL', iso2: 'POL', code: '48', trunk_code: ''},
        {name: 'Portugal', iso: 'PT', iso2: 'PRT', code: '351', trunk_code: ''},
        {name: 'Puerto Rico', iso: 'PR', iso2: 'PRI', code: '1', trunk_code: '1'},

        {name: 'Qatar', iso: 'QA', iso2: 'QAT', code: '974', trunk_code: ''},

        {name: 'Republic of the Congo	', iso: 'CG', iso2: 'COG', code: '242', trunk_code: ''},
        {name: 'Romania', iso: 'RO', iso2: 'ROU', code: '40', trunk_code: '0'},
        {name: 'Russia', iso: 'RU', iso2: 'RUS', code: '7', trunk_code: '8'},
        {name: 'Rwanda', iso: 'RW', iso2: 'RWA', code: '250', trunk_code: ''},

        {name: 'Saint Barthelemy', iso: 'BL', iso2: 'BLM', code: '590', trunk_code: ''},
        {name: 'Saint Helena', iso: 'SH', iso2: 'SHN', code: '290', trunk_code: ''},
        {name: 'Saint Kitts and Nevis', iso: 'KN', iso2: 'KNA', code: '1869', trunk_code: '1'},
        {name: 'Saint Lucia', iso: 'LC', iso2: 'LCA', code: '1758', trunk_code: '1'},
        {name: 'Saint Martin', iso: 'MF', iso2: 'MAF', code: '1599', trunk_code: '0'},
        {name: 'Saint Pierre and Miquelon', iso: 'PM', iso2: 'SPM', code: '508', trunk_code: ''},
        {name: 'Saint Vincent and the Grenadines', iso: 'VC', iso2: 'VCT', code: '1784', trunk_code: '1'},
        {name: 'Samoa', iso: 'WS', iso2: 'WSM', code: '685', trunk_code: ''},
        {name: 'San Marino', iso: 'SM', iso2: 'SMR', code: '378', trunk_code: ''},
        {name: 'Sao Tome and Principe', iso: 'ST', iso2: 'STP', code: '239', trunk_code: ''},
        {name: 'Saudi Arabia', iso: 'SA', iso2: 'SAU', code: '966', trunk_code: '0'},
        {name: 'Senegal', iso: 'SN', iso2: 'SEN', code: '221', trunk_code: ''},
        {name: 'Serbia', iso: 'RS', iso2: 'SRB', code: '381', trunk_code: '0'},
        {name: 'Seychelles', iso: 'SC', iso2: 'SYC', code: '248', trunk_code: ''},
        {name: 'Sierra Leone', iso: 'SL', iso2: 'SLE', code: '232', trunk_code: '0'},
        {name: 'Singapore', iso: 'SG', iso2: 'SGP', code: '65', trunk_code: ''},
        {name: 'Slovakia', iso: 'SK', iso2: 'SVK', code: '421', trunk_code: '0'},
        {name: 'Slovenia', iso: 'SI', iso2: 'SVN', code: '386', trunk_code: '0'},
        {name: 'Solomon Islands', iso: 'SB', iso2: 'SLB', code: '677', trunk_code: ''},
        {name: 'Somalia', iso: 'SO', iso2: 'SOM', code: '252', trunk_code: ''},
        {name: 'South Africa', iso: 'ZA', iso2: 'ZAF', code: '27', trunk_code: '0'},
        {name: 'South Korea', iso: 'KR', iso2: 'KOR', code: '82', trunk_code: '0'},
        {name: 'Spain', iso: 'ES', iso2: 'ESP', code: '34', trunk_code: ''},
        {name: 'Sri Lanka', iso: 'LK', iso2: 'LKA', code: '94', trunk_code: '0'},
        {name: 'Sudan', iso: 'SD', iso2: 'SDN', code: '249', trunk_code: '0'},
        {name: 'Suriname', iso: 'SR', iso2: 'SUR', code: '597', trunk_code: '0'},
        # {name: 'Svalbard', iso: 'SJ', iso2: 'SJM', code: '', trunk_code: ''},
        {name: 'Swaziland', iso: 'SZ', iso2: 'SWZ', code: '268', trunk_code: ''},
        {name: 'Sweden', iso: 'SE', iso2: 'SWE', code: '46', trunk_code: '0'},
        {name: 'Switzerland', iso: 'CH', iso2: 'CHE', code: '41', trunk_code: '0'},
        {name: 'Syria', iso: 'SY', iso2: 'SYR', code: '963', trunk_code: '0'},

        {name: 'Taiwan', iso: 'TW', iso2: 'TWN', code: '886', trunk_code: '0'},
        {name: 'Tajikistan', iso: 'TJ', iso2: 'TJK', code: '992', trunk_code: '8'},
        {name: 'Tanzania', iso: 'TZ', iso2: 'TZA', code: '255', trunk_code: '0'},
        {name: 'Thailand', iso: 'TH', iso2: 'THA', code: '66', trunk_code: '0'},
        {name: 'Timor-Leste', iso: 'TL', iso2: 'TLS', code: '670', trunk_code: ''},
        {name: 'Togo', iso: 'TG', iso2: 'TGO', code: '228', trunk_code: ''},
        {name: 'Tokelau', iso: 'TK', iso2: 'TKL', code: '690', trunk_code: ''},
        {name: 'Tonga', iso: 'TO', iso2: 'TON', code: '676', trunk_code: ''},
        {name: 'Trinidad and Tobago', iso: 'TT', iso2: 'TTO', code: '1868', trunk_code: '1'},
        {name: 'Tunisia', iso: 'TN', iso2: 'TUN', code: '216', trunk_code: ''},
        {name: 'Turkey', iso: 'TR', iso2: 'TUR', code: '90', trunk_code: '0'},
        {name: 'Turkmenistan', iso: 'TM', iso2: 'TKM', code: '993', trunk_code: '8'},
        {name: 'Turks and Caicos Islands', iso: 'TC', iso2: 'TCA', code: '1649', trunk_code: '1'},
        {name: 'Tuvalu', iso: 'TV', iso2: 'TUV', code: '688', trunk_code: ''},

        {name: 'Uganda', iso: 'UG', iso2: 'UGA', code: '256', trunk_code: '0'},
        {name: 'Ukraine', iso: 'UA', iso2: 'UKR', code: '380', trunk_code: '0'},
        {name: 'United Arab Emirates', iso: 'AE', iso2: 'ARE', code: '971', trunk_code: '0'},
        {name: 'United Kingdom', iso: 'GB', iso2: 'GBR', code: '44', trunk_code: '0'},
        {name: 'United States', iso: 'US', iso2: 'USA', code: '1', trunk_code: '1'},
        {name: 'Uruguay', iso: 'UY', iso2: 'URY', code: '598', trunk_code: '0'},
        {name: 'US Virgin Islands', iso: 'VI', iso2: 'VIR', code: '1340', trunk_code: '1'},
        {name: 'Uzbekistan', iso: 'UZ', iso2: 'UZB', code: '998', trunk_code: '0'},

        {name: 'Vanuatu', iso: 'VU', iso2: 'VUT', code: '678', trunk_code: ''},
        {name: 'Venezuela', iso: 'VE', iso2: 'VEN', code: '58', trunk_code: '0'},
        {name: 'Vietnam', iso: 'VN', iso2: 'VNM', code: '84', trunk_code: '0'},

        {name: 'Wallis and Futuna', iso: 'WF', iso2: 'WLF', code: '681', trunk_code: ''},
        # {name: 'West Bank', iso: '/', code: '970', trunk_code: ''},
        # {name: 'Western Sahara', iso: 'EH', iso2: 'ESH', code: '', trunk_code: ''},

        {name: 'Yemen', iso: 'YE', iso2: 'YEM', code: '967', trunk_code: '0'},

        {name: 'Zambia', iso: 'ZM', iso2: 'ZMB', code: '260', trunk_code: '0'},
        {name: 'Zimbabwe', iso: 'ZW', iso2: 'ZWE', code: '263', trunk_code: '0'}
      ]

    end
  end
end